### ISSUE TITLE
strict_types declared but usleep() receives a float

### ISSUE THREAD

**Issue by ugurarici** [Shopify/shopify-php-api#115]
# Issue summary

Shopify returns `Retry-After` header as a float. So when we run `usleep($retryAfter * 1000000);` on `Clients/Http.php` [Line 204](https://github.com/Shopify/shopify-php-api/blob/f756df032d3c9ddc625cc640746fbc362631b507/src/Clients/Http.php#L204) it throws a TypeError Exception as seen here: 

`TypeError: usleep(): Argument #1 ($microseconds) must be of type int, float given in /home/user/project/vendor/shopify/shopify-api/src/Clients/Http.php:204 `

## Expected behavior

Instead of throw an exception it should work and delays the program's execution for given microseconds.

## Actual behavior

What actually happens?

Throws a TypeError Exception as seen here: 

`TypeError: usleep(): Argument #1 ($microseconds) must be of type int, float given in /home/user/project/vendor/shopify/shopify-api/src/Clients/Http.php:204 `

## Steps to reproduce the problem

1. Throttle the api above your rate limit and you will encounter with TypeError Exception.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hi @ugurarici, great catch, we'll fix this!
