### ISSUE TITLE
Could not find the current session id in the cookies

### ISSUE THREAD

**Issue by pvkhanh1708** [Shopify/shopify-php-api#143]
# Issue summary

I get error when OAuth callback

Here is my code
```
OAuth::callback($cookies, $query, function (OAuthCookie $cookie) {
            setcookie(
                $cookie->getName(),
                $cookie->getValue(),
                $cookie->getExpire(),
                '',
                '',
                $cookie->isSecure(),
                $cookie->isHttpOnly()
            );
            return true;
        });
```

I get this error: 

Shopify\Exception\CookieNotFoundException
Could not find the current session id in the cookies

**Comment by prashantpdwivedi** [comment]
Hi,
I am also dealing with the same issue
Could you please let me know what are you passing in $cookie?

**Comment by raymundErank** [comment]
@pvkhanh1708  how did you get that $cookies variable?

**Comment by pvkhanh1708** [comment]
I am not passing this step, so I decided to use another package

**Comment by tuyutian** [comment]
I also encountered this error when submitting a listing check when using the officially provided cli library.
`Shopify\Exception\CookieNotFoundExceptionCould not find the current session id in the cookies`  
 Can you think that the officially provided sample cli is just a useless template that has not undergone any review and is just for normal users to complete the normal installation process ? Should I use the official template as the base template for developing an app?

**Comment by sachincr7** [comment]
Hey this is how im setting my cookies in /auth route
```
return redirect(OAuth::begin($request->query('shop'), '/auth/callback', false, function (OAuthCookie $cookie) use ($request) {
            Cookie::queue($cookie->getName(), $cookie->getValue(), $cookie->getExpire(), '/', env('SHOPIFY_APP_HOST_NAME'), 
            $request->secure());
            return true;
}));
```
When redirect to /auth/callback, this is how im creating the session.

 $shopSession = OAuth::callback($request->cookie(), $request->query());

When I install the app for the first time it seems to be working fine, but when I try to install for the second time.

![image](https://user-images.githubusercontent.com/25481140/182832026-0cb3fc6e-109a-4fcd-a6e3-1418a62aebc1.png)

**Comment by badandboy** [comment]
i have the same question,  do you resolve it ?

**Comment by badandboy** [comment]
> Hey this is how im setting my cookies in /auth route
> 
> ```
> return redirect(OAuth::begin($request->query('shop'), '/auth/callback', false, function (OAuthCookie $cookie) use ($request) {
>             Cookie::queue($cookie->getName(), $cookie->getValue(), $cookie->getExpire(), '/', env('SHOPIFY_APP_HOST_NAME'), 
>             $request->secure());
>             return true;
> }));
> ```
> 
> When redirect to /auth/callback, this is how im creating the session.
> 
> $shopSession = OAuth::callback($request->cookie(), $request->query());
> 
> When I install the app for the first time it seems to be working fine, but when I try to install for the second time.
> 
> ![image](https://user-images.githubusercontent.com/25481140/182832026-0cb3fc6e-109a-4fcd-a6e3-1418a62aebc1.png)

set setCookieFunction = null, it work for me

**Comment by vaimeo** [comment]
Hi, if you have modified the store table then there is a error on the save store query function on app/app/Lib/DbSessionStorage.php at line 89, insert all your field which don't have default value will fix this issue.

**Comment by kevin-ryser** [comment]
Hi, are you guys sure you've a SSL certificate installed? (Https?). Otherwise I believe the default setcookie function will not set the cookies.

**Comment by shahbaz-mehar** [comment]
Any update on it?

**Comment by ketanm24** [comment]
I am facing this issue when I add additional scopes to the app.

**Comment by rafaelstz** [comment]
I fix it by adjusting the code like this:

```php
Route::get('/api/auth/callback', function (Request $request) {
    try {
        $cookies = $request->cookie();
        if ($request->cookie() == null) {
            $cookies = $_COOKIE;
        }
        $session = OAuth::callback(
            $cookies,
            $request->query(),
            ['App\Lib\CookieHandler', 'saveShopifyCookie'],
        );
    } catch (Exception $e) {
        Log::warning('Failed to authenticate: ' . $e->getMessage());

        return redirect('/api/auth?shop=' . $request->query('shop'));
    }
...
```

**Comment by robertiulianstoica** [comment]
I am still having this issue on symfony 5.4, i've created a service which handles the shopify plugin.

`
namespace App\Merchant\Service;

use App\Merchant\Dto\OrderResponse;
use Doctrine\Persistence\ManagerRegistry;
use Shopify\Auth\FileSessionStorage;
use Shopify\Auth\OAuth;
use Shopify\Auth\Session;
use Shopify\Clients\Rest;
use Shopify\Context;
use Shopify\Utils;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class MerchantService
{
    private $session;

    public function __construct(
        ContainerBagInterface $params,
        HttpClientInterface $http_client,
        ManagerRegistry $doctrine
    ) {
        Context::initialize(
            apiKey: $params->get('merchant_client_id'),
            apiSecretKey: $params->get('merchant_client_secret'),
            scopes: $params->get('merchant_scopes'),
            hostName: $params->get('merchant_hostname'),
            sessionStorage: new FileSessionStorage(),
            apiVersion: '2023-01',
            isEmbeddedApp: true,
            isPrivateApp: false,
        );
    }

    public function authenticate(string $shop): string
    {
        return OAuth::begin(
            $shop,
            'shopify/callback',
            true
        );
    }

    public function callback(array $cookies, array $query)
    {
        return OAuth::callback(
            $cookies,
            $query
        );
    }
    }
    `
I have tried switching to an older API version but it still deos not work.

`
namespace App\Merchant\Controller;

use App\Customer\Service\CustomerService;
use App\Merchant\Service\MerchantService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Stopwatch\Stopwatch;

class AuthenticationController extends AbstractController
{
    #[Route('/oauth', name: 'oauth', methods: ['GET'])]
    public function oauth(
        Request $request,
        MerchantService $merchant,
        ContainerBagInterface $params,
    ): Response {
        return $this->redirect($merchant->authenticate($request->get('shop')));
    }

    #[Route('/callback', name: 'callback', methods: ['GET'])]
    public function callback(
        Request $request,
        Stopwatch $stopwatch,
        MerchantService $merchant,
        CustomerService $customer,
    ): Response {
        $cookies = $request->cookies->all();
        if (null == $cookies) {
            $cookies = $_COOKIE;
        }

        $session = $merchant->callback($cookies, $request->query->all());

        $customer->saveAccessToken($session->getShop(), $session->getAccessToken());

        return $this->redirectToRoute('install', $request->query->all());
    }
}
`
