### ISSUE TITLE
[PHP 8.2] Issue with dynamic properties

### ISSUE THREAD

**Issue by bakura10** [Shopify/shopify-php-api#237]
Hi,

As of today, the library dynamically create class properties, such as [here](https://github.com/Shopify/shopify-api-php/blob/main/src/Auth/Session.php#L31).

This has been deprecated in PHP 8.2. Current version therefore lead to warning errors.

Thanks :)

**Comment by fredden** [comment]
Related: https://github.com/Shopify/shopify-api-php/pull/250
