### ISSUE TITLE
Enable trial period billing using trialDays parameter in EnsureBilling class

### ISSUE THREAD

**Issue by visionlabit** [Shopify/shopify-php-api#240]
## Overview

The Shopify PHP app template already supports, using the EnsureBilling class, the management of some Billing APIs mutations.
Since the underlying billing mutations already support the usage of "trialDays" parameter to enable a trial period of the app (https://shopify.dev/apps/billing/purchase-adjustments/free-trials), I would like to be able to define its value in the shopify.php config file and use it through the EnsureBilling functions as we can do for all the other billing parameters.

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

The EnsureBilling class enables setting up easily the Shopify app billing using middleware.
Since the billing API mutations used by EnsureBilling's functions already support for the trial period using the "trialDays" parameter, it would be convenient to be able to use all the mutations' native options also through EnsureBilling's functions which wrap them.

...

### Area

- [ ] Billing

---

## Checklist

- [ ] Add "trialDays" parameter to shopify.php config file example
- [ ] Edit requestRecurringPayment and requestOneTimePayment functions to use and support the new trialDays parameter
- [ ] Edit RECURRING_PURCHASE_MUTATION and ONE_TIME_PURCHASE_MUTATION to support the new trialDays parameter

**Comment by rafaelstz** [comment]
@visionlabit  It's done here https://github.com/Shopify/shopify-app-template-php/pull/412

**Comment by rafaelstz** [comment]
I agree, let's see what they think about it. I just moved it to the config.
