### ISSUE TITLE
Useless code

### ISSUE THREAD

**Issue by thanghv** [Shopify/shopify-php-api#376]
## Overview/summary

Can you please let me know those code for what? 

https://github.com/Shopify/shopify-api-php/blob/dc06610e60e839b41e07951f90658429a938a4e4/src/Auth/OAuth.php#L161

I mean, set state cookie in callback for what?

...

## Motivation

> What inspired this enhancement?

...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [ ] I have described this enhancement in a way that is actionable (if possible)

**Comment by Arkham** [comment]
Hi there, can you clarify your question?
