### ISSUE TITLE
Need to get state cookie

### ISSUE THREAD

**Issue by thanghv** [Shopify/shopify-php-api#377]
## Overview/summary

Can you please add more parameters to set state cookie, for example: shop domain. 
"state" value are not good enough.

At this line:

https://github.com/Shopify/shopify-api-php/blob/dc06610e60e839b41e07951f90658429a938a4e4/src/Auth/OAuth.php#L71

...

## Motivation

> What inspired this enhancement?

...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [ ] I have described this enhancement in a way that is actionable (if possible)

**Comment by Arkham** [comment]
Hi there, can you provide an example on what you're trying to achieve?
