### ISSUE TITLE
graphQL Admin AOPI return nos data

### ISSUE THREAD

**Issue by jonyking** [Shopify/shopify-php-api#389]
Hello,

I'm trying to get data via the Graphql Admin API. The problem is that there is not return data. I get only successfully request ....

At first: the documentation is the badest I've ever seen and the authentication process is poor to.

My test code:

```

Context::initialize(
      apiKey: 'xxxxxx',
      apiSecretKey: 'xxxx',
      scopes: ['read_all_orders'],
      hostName: 'xxxxx',
      sessionStorage: new FileSessionStorage('/tmp/php_sessions'),
      apiVersion: '2024-10',
      isEmbeddedApp: true,
      isPrivateApp: false,
    );

    $client = new Graphql("xxxx.com", 'xxxxx');
    $query = <<<QUERY
  query {
    orders(first: 10, query: "created_at:>2024-01-01") {
      edges {
        node {
          id
          updatedAt
        }
      }
    }
  }
QUERY;

    $response = $client->query($query);
```
The only result that I get is the following:

`Shopify\Clients\HttpResponse Object ( [reasonPhrase:GuzzleHttp\Psr7\Response:private] => OK [statusCode:GuzzleHttp\Psr7\Response:private] => 200 [headers:GuzzleHttp\Psr7\Response:private] => Array ( [Date] => Array ( [0] => Tue, 26 Nov 2024 15:08:32 GMT ) [Content-Type] => Array ( [0] => application/json; charset=utf-8 ) [Transfer-Encoding] => Array ( [0] => chunked ) [Connection] => Array ( [0] => keep-alive ) [x-sorting-hat-podid] => Array ( [0] => 265 ) [x-sorting-hat-shopid] => Array ( [0] => 9324757077 ) [vary] => Array ( [0] => Accept-Encoding ) [referrer-policy] => Array ( [0] => origin-when-cross-origin ) [x-frame-options] => Array ( [0] => DENY ) [x-shopid] => Array ( [0] => 9324757077 ) [x-shardid] => Array ( [0] => 265 ) [x-stats-userid] => Array ( [0] => ) [x-stats-apiclientid] => Array ( [0] => 171528290305 ) [x-stats-apipermissionid] => Array ( [0] => 787760906506 ) [x-shopify-api-version] => Array ( [0] => 2024-10 ) [content-language] => Array ( [0] => en ) [strict-transport-security] => Array ( [0] => max-age=7889238 ) [x-request-id] => Array ( [0] => 0f01fc21-0864-4528-a8f5-6454404b9b79-1732633712 ) [server-timing] => Array ( [0] => processing;dur=102, graphql;desc="admin/query/other" [1] => cfRequestDuration;dur=161.999941 ) [content-security-policy] => Array ( [0] => default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com/ https://cdn.shopifycdn.net/ https://checkout.pci.shopifyinc.com/ https://api.stripe.com/ https://mpsnare.iesnare.com/ https://appcenter.intuit.com/ https://www.paypal.com/ https://js.braintreegateway.com/ https://c.paypal.com/ https://maps.googleapis.com/ https://www.google-analytics.com/ https://v.shopify.com/ 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=query&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fgraphql&source%5Bsection%5D=admin_api&source%5Buuid%5D=0f01fc21-0864-4528-a8f5-6454404b9b79-1732633712 ) [x-content-type-options] => Array ( [0] => nosniff ) [x-download-options] => Array ( [0] => noopen ) [x-permitted-cross-domain-policies] => Array ( [0] => none ) [x-xss-protection] => Array ( [0] => 1; mode=block; report=/xss-report?source%5Baction%5D=query&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fgraphql&source%5Bsection%5D=admin_api&source%5Buuid%5D=0f01fc21-0864-4528-a8f5-6454404b9b79-1732633712 ) [x-dc] => Array ( [0] => gcp-europe-west3,gcp-europe-west3,gcp-europe-west3 ) [Alt-Svc] => Array ( [0] => h3=":443"; ma=86400 ) [CF-Cache-Status] => Array ( [0] => DYNAMIC ) [Report-To] => Array ( [0] => {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=TM76rVz0AoJRBld2ni3V%2BQr9%2B%2BpCgylVKfJ8aiapP5ds%2BOkvBMB4jr20ITfk8zQ61f28oO20qPOjOHREVzAeAfUvuTfmMwMmLy0xAbnfxpZwyjcI4ZFW1hDEHzAwPQO%2Bimfg3%2FDX8aA%2B"}],"group":"cf-nel","max_age":604800} ) [NEL] => Array ( [0] => {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800} ) [Server] => Array ( [0] => cloudflare ) [CF-RAY] => Array ( [0] => 8e8acb5ecfa0a5fa-FRA ) ) [headerNames:GuzzleHttp\Psr7\Response:private] => Array ( [date] => Date [content-type] => Content-Type [transfer-encoding] => Transfer-Encoding [connection] => Connection [x-sorting-hat-podid] => x-sorting-hat-podid [x-sorting-hat-shopid] => x-sorting-hat-shopid [vary] => vary [referrer-policy] => referrer-policy [x-frame-options] => x-frame-options [x-shopid] => x-shopid [x-shardid] => x-shardid [x-stats-userid] => x-stats-userid [x-stats-apiclientid] => x-stats-apiclientid [x-stats-apipermissionid] => x-stats-apipermissionid [x-shopify-api-version] => x-shopify-api-version [content-language] => content-language [strict-transport-security] => strict-transport-security [x-request-id] => x-request-id [server-timing] => server-timing [content-security-policy] => content-security-policy [x-content-type-options] => x-content-type-options [x-download-options] => x-download-options [x-permitted-cross-domain-policies] => x-permitted-cross-domain-policies [x-xss-protection] => x-xss-protection [x-dc] => x-dc [alt-svc] => Alt-Svc [cf-cache-status] => CF-Cache-Status [report-to] => Report-To [nel] => NEL [server] => Server [cf-ray] => CF-RAY ) [protocol:GuzzleHttp\Psr7\Response:private] => 1.1 [stream:GuzzleHttp\Psr7\Response:private] => GuzzleHttp\Psr7\Stream Object ( [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #13 [size:GuzzleHttp\Psr7\Stream:private] => [seekable:GuzzleHttp\Psr7\Stream:private] => 1 [readable:GuzzleHttp\Psr7\Stream:private] => 1 [writable:GuzzleHttp\Psr7\Stream:private] => 1 [uri:GuzzleHttp\Psr7\Stream:private] => php://temp [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array ( ) ) [requestId:Shopify\Clients\HttpResponse:private] => 0f01fc21-0864-4528-a8f5-6454404b9b79-1732633712 )`

But there is no error message, no result ..... 

We use the offical PHP SDK

**Comment by lizkenyon** [comment]
Hi there 👋 

I would recommend checking out[this example code](https://github.com/Shopify/shopify-app-template-php/blob/dabab615b1135cc4fa831e8496decb6a4b379a04/web/app/Lib/ProductCreator.php#L24-L47).
