### ISSUE TITLE
Callback fetchAccessToken problem

### ISSUE THREAD

**Issue by novayadi85** [Shopify/shopify-php-api#93]
# Issue summary

Fatal error: Uncaught TypeError: Return value of Shopify\Clients\HttpClientFactory::client() must be an instance of Psr\Http\Client\ClientInterface, instance of GuzzleHttp\Client returned in

This happen in callback method when try to fetchAccessToken, any clue why this happen ?

**Comment by swayoleg** [comment]
The same issue for me
            "name": "shopify/shopify-api",
            "version": "v5.0.0",


            "name": "guzzlehttp/guzzle",
            "version": "7.7.0",

Composer version 2.5.5 2023-03-21 11:50:05
PHP 8.1.11

@novayadi85 

Can you please share your versions?
